### ISSUE TITLE
Gerador de Código randômicos 

### ISSUE THREAD

**Issue by thaylongs** [arthurgregorio/web-budget#206]
Olá, observei que na sua classe:  `br.com.webbudget.infraestructure.configurationApplicationUtils` tem um método chamado `createRamdomCode`, que gera código aleatórios dentro de um while. Não sei como esse método é utilizado em todos os lugares, mas aparentemente ele é utilizado para gerar identificadores únicos.  A partir dessa premissa, eu gostaria de lhe dar uma  dica, no Java por padrão já tem uma classe especifico para isso: `java.util.UUID.randomUUID().toString()`. 

Referência: http://www.javapractices.com/topic/TopicAction.do?Id=56

**Comment by arthurgregorio** [comment]
Obrigado pela sugestão!

Mas o fato de eu ter um método próprio para gerar os códigos é devido a forma como eu gero, basicamente preciso definir um range para ele e dizer se quero apenas números ou letras, com o UUID não tenho esta possibilidade a não "escovando" a string gerada, que me daria mais trabalho em alguns casos.
