### ISSUE TITLE
Não consigo instalar

### ISSUE THREAD

**Issue by lippe14** [arthurgregorio/web-budget#288]
Boa tarde, não consigo instalar o app.

Tem como me enviar um passo-a-passo??

**Comment by fauker** [comment]
@arthurgregorio segui o tutorial do seguinte [post](http://arthurgregorio.eti.br/blog/geral/webbudget-agora-com-docker/), porém não tive sucesso.

Instalei a imagem do banco e a da aplicação. Ela sobe sem erros, porém, não consigo acessá-la através do ip que o comando `docker inspect --format '{{ .NetworkSettings.IPAddress }}' wb-app` me fornece (`http://172.17.0.3`) na porta 8080.

Vc passou por isso alguma vez?

**Comment by fauker** [comment]
@arthurgregorio o tutorial de instalação via Docker ainda funciona?
Tentei pelo Windows e pelo Mac e não tive sucesso com nenhum.
O servidor sobe e tudo mais, porém não consigo acessar a app pelo link exposto pelo Docker.

![image](https://user-images.githubusercontent.com/7989766/39665673-3ddb607e-506e-11e8-8647-55c60c167065.png)

![image](https://user-images.githubusercontent.com/7989766/39665677-44cfbe84-506e-11e8-8482-a3d2fc25a646.png)

**Comment by deleonsousa** [comment]
@fauker passa a linha de comando vc usou pra subir o container, pode ajudar na resolução.

**Comment by fauker** [comment]
@deleonsousa 

`docker run --name wb-db -it -p 3306:3306 -d arthurgregorio/webbudget-db`
`docker run --name wb-app --link wb-db:db -it -p 8080:8080 -d arthurgregorio/webbudget-app`
`docker inspect --format '{{ .NetworkSettings.IPAddress }}' wb-app`

Tentei através da outra opção com `docker-compose.yml`, mas também não funcionou.

Eu segui através deste [post](http://arthurgregorio.eti.br/blog/geral/webbudget-agora-com-docker/).

**Comment by arthurgregorio** [comment]
Olá, estive sem tempo para atualizar os detalhes mais técnicos do projeto.

Criei uma issue (#289) para que uma nova imagem do docker seja gerada, a imagem que vc utilizou apresentava alguns problemas na hora de disponibilizar o serviço na porta correta.

Com a nova imagem que gerei as coisas ficaram mais fáceis, tente usá-la com o comando abaixo:

```
docker run --name webbudget -itd -p 8443:8443 arthurgregorio/web-budget-docker
```

Depois é só acessar pelo browser https://localhost:8443 e utilizar o usuário *admin* com senha *admin*

Me avise se der certo para que eu possa encerrar esta issue.

**Comment by fauker** [comment]
Legal, @arthurgregorio! Agora funcionou. Valeu!!
