### ISSUE TITLE
Versão em Electron

### ISSUE THREAD

**Issue by fabianski7** [arthurgregorio/web-budget#471]
Utilizar o docker não é difícil, especialmente da maneira muito bem documentada que você fez, mas acho que pode afastar algum usuário novo que queira testar o software pela primeira vez e não tenha o docker instalado.

Uma versão em electron poderia ser uma boa solução para isso. Manteria o funcionamento offline e ainda possibilitaria empacotamento para várias distros.

**Comment by arthurgregorio** [comment]
Um versão electron do wB seria tecnicamente inviável no momento, teria que haver uma mudança gigantesca da parte do frontend e ainda mais ajustes de tudo que esta dentro dos beans JSF serem expostos em uma API REST.

Olhando do ponto de vista de esforço, impossível no momento atual.

Porém, caso queira contribuir para o projeto, estamos aberto a contribuições.
