### ISSUE TITLE
Erro ao subir aplicação utilizando docker-compose

### ISSUE THREAD

**Issue by pillaedu** [arthurgregorio/web-budget#488]
Ao executar docker-compose up o container webbudget_postgres falha ao criar a database segundo log abaixo:

webbudget_postgres    | The files belonging to this database system will be owned by user "postgres".
webbudget_postgres    | This user must also own the server process.
webbudget_postgres    | 
webbudget_postgres    | The database cluster will be initialized with locale "en_US.utf8".
webbudget_postgres    | The default database encoding has accordingly been set to "UTF8".
webbudget_postgres    | The default text search configuration will be set to "english".
webbudget_postgres    | 
webbudget_postgres    | Data page checksums are disabled.
webbudget_postgres    | 
webbudget_postgres    | fixing permissions on existing directory /var/lib/postgresql/data ... ok
webbudget_postgres    | creating subdirectories ... ok
webbudget_postgres    | selecting dynamic shared memory implementation ... posix
webbudget_postgres    | selecting default max_connections ... 100
webbudget_postgres    | selecting default shared_buffers ... 128MB
webbudget_postgres    | selecting default time zone ... UTC
webbudget_postgres    | creating configuration files ... ok
webbudget_postgres    | running bootstrap script ... ok
webbudget_postgres    | performing post-bootstrap initialization ... sh: locale: not found
webbudget_postgres    | 2021-02-05 11:42:21.739 UTC [29] WARNING:  no usable system locales were found
webbudget_postgres    | ok
webbudget_postgres    | syncing data to disk ... ok
webbudget_postgres    | 
webbudget_postgres    | initdb: warning: enabling "trust" authentication for local connections
webbudget_postgres    | You can change this by editing pg_hba.conf or using the option -A, or
webbudget_postgres    | --auth-local and --auth-host, the next time you run initdb.
webbudget_postgres    | 
webbudget_postgres    | Success. You can now start the database server using:
webbudget_postgres    | 
webbudget_postgres    |     pg_ctl -D /var/lib/postgresql/data -l logfile start
webbudget_postgres    | 
webbudget_postgres    | waiting for server to start....2021-02-05 11:42:25.816 UTC [34] LOG:  starting PostgreSQL 12.5 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.2.1_pre1) 10.2.1 20201203, 64-bit
webbudget_postgres    | 2021-02-05 11:42:25.819 UTC [34] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
webbudget_postgres    | 2021-02-05 11:42:25.872 UTC [35] LOG:  database system was shut down at 2021-02-05 11:42:23 UTC
webbudget_postgres    | 2021-02-05 11:42:25.877 UTC [34] LOG:  database system is ready to accept connections
webbudget_postgres    |  done
webbudget_postgres    | server started
webbudget_postgres    | 2021-02-05 11:42:25.940 UTC [44] LOG:  statement: SELECT 1 FROM pg_database WHERE datname = 'webbudget' ;
webbudget_postgres    | 2021-02-05 11:42:25.972 UTC [46] LOG:  statement: CREATE DATABASE "webbudget" ;
webbudget_postgres    | CREATE DATABASE
webbudget_postgres    | 
webbudget_postgres    | 
webbudget_postgres    | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/1-create-schemas.sql
webbudget_postgres    | psql:/docker-entrypoint-initdb.d/1-create-schemas.sql: error: could not read from input file: Is a directory
webbudget_postgres exited with code 1

**Comment by arthurgregorio** [comment]
Corrigido, a linha do script apontava para um arquivo que não existia.

**Comment by pillaedu** [comment]
Onde posso encontrar a imagem docker atualizada? Rodei aqui e o problema continua....
