### ISSUE TITLE
Diário do carro

### ISSUE THREAD

**Issue by arthurgregorio** [arthurgregorio/web-budget#86]
Criar uma forma de armazenar informações referentes as manutenções e despesas com o carro, algo como um diário onde seja possível mitigar os gastos com o veículo e também ter um histórico dos serviços realizados, garantias e tudo mais.

**Comment by absantanna2412** [comment]
Arthur,

Você poderia generalizar um pouco essa funcionalidade, porque restringi-la a apenas carros?

Posso querer fazer o mesmo com uma Piscina, Jardim, Lancha ou Animais de Estimação. Imagine o sistema sendo utilizado por um administrador de um condomínio, onde ele queria manter um diário das despesas com a Quadra de Esportes, Portaria, Elevadores, etc...

As possibilidades são infinitas.

A sugestão seria:

Diário de Bens
Tipo de Bem (Automóvel, Animal, Local, Etc..)
Cadastro dos Bens
Cadastro de Ocorrências.

Abraços,

**Comment by arthurgregorio** [comment]
Interessante sua colocação.

Como a versão já esta atrasada mesmo, vou avaliar o impacto da mudança pois esta funcionalidade já esta quase toda pronta.

**Comment by arthurgregorio** [comment]
Processo finalizado no commit 54e3551
